const detectLikelyComplexity = (code: string) => {
  const normalized = code.toLowerCase();
  if (normalized.includes("sort(")) {
    return {
      time: "O(N log N)",
      space: "O(1) to O(N)",
    };
  }

  const hasNestedFor = /for\s*\([^)]*\)\s*\{?[\s\S]{0,300}for\s*\(/i.test(code);
  if (hasNestedFor) {
    return {
      time: "O(N^2)",
      space: "O(1)",
    };
  }

  return {
    time: "O(N)",
    space: "O(1) to O(N)",
  };
};

const getTopicHint = (topic: string) => {
  const t = topic.toLowerCase();
  if (t.includes("two pointer")) {
    return "Try maintaining one pointer from each side and move the one that is currently limiting progress.";
  }
  if (t.includes("sliding window")) {
    return "Think about expanding the window to satisfy the condition, then shrinking it while still valid.";
  }
  if (t.includes("tree") || t.includes("graph")) {
    return "Choose traversal first (DFS/BFS), then define exactly what state you need per node.";
  }
  if (t.includes("dynamic programming") || t.includes("dp")) {
    return "Define your state and transition clearly before coding; write the recurrence in plain English first.";
  }
  return "Focus on identifying the smallest reusable pattern in this problem before writing full code.";
};

const parseFunctionName = (code: string) => {
  const match = code.match(
    /(?:function\s+([A-Za-z0-9_]+)|const\s+([A-Za-z0-9_]+)\s*=\s*\()/,
  );
  return match?.[1] || match?.[2] || "solve";
};

export const getAIHint = async (
  problemTitle: string,
  topic: string,
  difficulty: string,
) => {
  return [
    `Problem: ${problemTitle}`,
    `Difficulty: ${difficulty}`,
    getTopicHint(topic),
    "Start with a tiny dry run and verify your invariant after each step.",
  ].join("\n");
};

export const getPatternExplanation = async (topic: string) => {
  return `### ${topic}\n\n- Core intuition: Reduce the problem to a repeatable local rule and apply it consistently.\n- Edge cases: Empty input, single element, duplicate-heavy input, and boundary indexes.\n- Pro tip: State your invariant out loud first; interviewers value reasoning before code.`;
};

export const getAICodeReview = async (
  code: string,
  problemTitle: string,
  topic: string,
) => {
  const complexity = detectLikelyComplexity(code);
  const hasComments = /\/\/|\/\*/.test(code);
  const structured = {
    verdict: code.length > 30 ? "GOOD" : "NEEDS WORK",
    summary: `Review for ${problemTitle} (${topic}) generated by local analyzer.`,
    efficiency: {
      timeComplexity: complexity.time,
      timeExplanation:
        "Estimated from common constructs like sorting and nested loops.",
      spaceComplexity: complexity.space,
      spaceExplanation:
        "Estimated from visible data structure usage in the submitted code.",
      isOptimal: complexity.time !== "O(N^2)",
      optimalNote:
        complexity.time === "O(N^2)"
          ? "Consider reducing nested iteration using hashing or two pointers if applicable."
          : "Looks reasonable for a first-pass solution.",
    },
    logic: {
      isCorrect: true,
      explanation:
        "Local static review cannot execute tests; validate with edge-case tests to confirm correctness.",
      edgeCases: [
        {
          case: "Empty input",
          handled: false,
          note: "Ensure early return for empty structures.",
        },
        {
          case: "Single element",
          handled: true,
          note: "Most iterative solutions should handle this naturally.",
        },
      ],
    },
    cleanCode: [
      {
        suggestion: hasComments
          ? "Keep comments focused on invariants and non-obvious decisions."
          : "Add one short comment explaining your key invariant.",
        example:
          "// Invariant: window [left, right] always satisfies condition X",
      },
    ],
    proTip:
      "When discussing your solution, explain trade-offs first, then implementation details.",
  };
  return { type: "structured", data: structured };
};

export const evaluateCode = async (
  code: string,
  problemTitle: string,
  topic: string,
  difficulty: string,
  language: string,
) => {
  const complexity = detectLikelyComplexity(code);
  const isLongEnough = code.trim().length > 30;
  return {
    isCorrect: isLongEnough,
    verdict: isLongEnough ? "ACCEPTED" : "WRONG_ANSWER",
    verdictMessage: isLongEnough
      ? `Static local evaluation for ${problemTitle} (${topic}, ${difficulty}, ${language}).`
      : "Solution appears incomplete. Add more implementation detail.",
    failingCase: {
      input: isLongEnough ? null : "Minimal non-trivial input",
      expected: isLongEnough ? null : "Valid output",
      actual: isLongEnough ? null : "Insufficient implementation",
    },
    complexity: {
      time: complexity.time,
      timeExplanation: "Estimated from loops/sorting in the submitted code.",
      space: complexity.space,
      spaceExplanation: "Estimated from visible data structures.",
    },
    optimalComplexity: {
      time: "O(N)",
      space: "O(1) to O(N)",
      isCurrentOptimal: complexity.time !== "O(N^2)",
      explanation:
        complexity.time === "O(N^2)"
          ? "Try hashing, prefix structures, or two pointers to avoid nested loops."
          : "Current complexity is likely acceptable for common constraints.",
    },
    betterApproaches:
      complexity.time === "O(N^2)"
        ? [
            {
              name: "Hash-based optimization",
              timeComplexity: "O(N)",
              spaceComplexity: "O(N)",
              description:
                "Store prior computations in a map/set to avoid repeated scans.",
              pseudocode:
                "init map\nfor each item:\n  check needed value in map\n  update map",
            },
          ]
        : [],
    edgeCases: [
      { case: "Empty input", handled: false },
      { case: "Single element", handled: true },
      { case: "Duplicate values", handled: true },
    ],
    score: isLongEnough ? 72 : 35,
    feedback:
      "This evaluation is generated locally without external AI providers; run targeted tests to verify behavior.",
    originality: {
      verdict: "HUMAN",
      confidence: 50,
      signals: [
        "Local analyzer uses heuristic checks only; verdict is low confidence.",
      ],
      explanation:
        "No external model is used; originality classification is conservative.",
    },
  };
};

export const getAlgoTracing = async (code: string, problemTitle: string) => {
  const fnName = parseFunctionName(code);
  return {
    sampleInput: "nums = [2, 7, 11, 15], target = 9",
    expectedOutput: "[0, 1]",
    approach: `Trace core control flow for ${fnName} on a tiny representative input.`,
    steps: [
      {
        step: 1,
        phase: "INIT",
        codeLine: "initialize variables",
        narrative: `Set up the initial state for ${problemTitle}.`,
        thinking: "A clear initial state prevents hidden edge-case bugs later.",
        variables: [{ name: "i", value: "0", changed: true }],
        dataStructure: {
          type: "array",
          label: "Input",
          items: [
            { value: "2", state: "active" },
            { value: "7", state: "default" },
            { value: "11", state: "default" },
            { value: "15", state: "default" },
          ],
        },
      },
      {
        step: 2,
        phase: "CHECK",
        codeLine: "evaluate condition",
        narrative:
          "Check whether the current state satisfies the target condition.",
        thinking: "Make each condition explicit so failures are easy to debug.",
        variables: [{ name: "conditionMet", value: "true", changed: true }],
        dataStructure: {
          type: "array",
          label: "Input",
          items: [
            { value: "2", state: "highlight" },
            { value: "7", state: "highlight" },
            { value: "11", state: "done" },
            { value: "15", state: "done" },
          ],
        },
      },
      {
        step: 3,
        phase: "RETURN",
        codeLine: "return result",
        narrative: "Return the computed answer once the condition is met.",
        thinking:
          "Returning immediately after success keeps logic simple and efficient.",
        variables: [{ name: "result", value: "[0,1]", changed: true }],
        dataStructure: {
          type: "array",
          label: "Output",
          items: [
            { value: "0", state: "highlight" },
            { value: "1", state: "highlight" },
          ],
        },
      },
    ],
  };
};

export const getAIRecommendations = async (
  solvedProblems: Array<{
    title: string;
    topic: string;
    difficulty: string;
    score: number;
    isOptimal: boolean;
  }>,
  weakTopics: string[],
  allTopics: string[],
  context?: {
    revisionReminders?: Array<{
      id: string;
      title: string;
      topicName: string;
      daysSince: number;
    }>;
    weakTopicBreakdown?: Array<{
      name: string;
      avgTimeSpent?: number;
      completionPct?: number;
    }>;
    solvedLast7d?: number;
    solvedLast30d?: number;
  },
) => {
  // Calculate experience metrics
  const totalSolved = solvedProblems.length;
  const avgScore =
    totalSolved > 0
      ? solvedProblems.reduce((sum, p) => sum + (p.score || 0), 0) / totalSolved
      : 0;
  const optimalCount = solvedProblems.filter((p) => p.isOptimal).length;

  // Pick candidate topics (prioritize weak topics)
  const candidateTopics = (weakTopics.length ? weakTopics : allTopics).slice(
    0,
    5,
  );

  // Personalized suggested problems (simulate with topic, difficulty, and reason)
  const suggestedProblems = candidateTopics.map((topicName, index) => {
    // Personalize difficulty: if user is experienced, suggest harder problems
    let difficulty = "EASY";
    if (avgScore > 70 && totalSolved > 20) {
      difficulty = index < 2 ? "MEDIUM" : "HARD";
    } else if (avgScore > 40 && totalSolved > 10) {
      difficulty = index < 3 ? "EASY" : "MEDIUM";
    }
    return {
      title: `${topicName} Practice #${index + 1}`,
      reason: weakTopics.includes(topicName)
        ? "You have lower mastery here; deliberate practice should improve speed and confidence."
        : "Balanced exposure helps maintain breadth across topics.",
      topic: topicName,
      difficulty,
    };
  });

  const latestRevision = context?.revisionReminders?.[0];
  const weakestTopicName =
    weakTopics[0] || context?.weakTopicBreakdown?.[0]?.name;
  const weakestTopicStats =
    weakestTopicName && context?.weakTopicBreakdown
      ? context.weakTopicBreakdown.find(
          (topic) => topic.name === weakestTopicName,
        )
      : undefined;
  const hasMomentumGap = (context?.solvedLast7d ?? 0) === 0 && totalSolved >= 1;

  const nextAction = latestRevision
    ? {
        mode: "REVISION" as const,
        title: `Review ${latestRevision.title}`,
        topic: latestRevision.topicName,
        reason: `This problem is already due for review after ${latestRevision.daysSince} days.`,
        cta: "Open review queue",
        difficulty: "REVIEW",
        estimatedMinutes: Math.max(
          10,
          Math.min(45, latestRevision.daysSince * 5),
        ),
      }
    : weakestTopicName
      ? {
          mode: "WEAKNESS" as const,
          title: `Practice ${weakestTopicName}`,
          topic: weakestTopicName,
          reason: weakestTopicStats
            ? weakestTopicStats.avgTimeSpent
              ? `This topic is slowing you down at about ${weakestTopicStats.avgTimeSpent} minutes per solved problem.`
              : weakestTopicStats.completionPct !== undefined
                ? `This topic is only ${Math.round(weakestTopicStats.completionPct)}% complete.`
                : "This is one of your weakest topics right now."
            : "This is one of your weakest topics right now.",
          cta: "Start practice",
          difficulty: suggestedProblems[0]?.difficulty || "EASY",
          estimatedMinutes: Math.max(20, weakestTopicStats?.avgTimeSpent || 20),
        }
      : hasMomentumGap
        ? {
            mode: "BUILD_MOMENTUM" as const,
            title: "Solve one easy problem",
            topic: allTopics[0] || "Warm-up",
            reason:
              "You have recent activity, but not enough momentum this week. Keep the streak alive with a short warm-up.",
            cta: "Pick an easy win",
            difficulty: "EASY",
            estimatedMinutes: 20,
          }
        : {
            mode: "BALANCED" as const,
            title: "Mix review with new practice",
            topic: allTopics[0] || "Balanced practice",
            reason:
              "You are in a steady state. Blend one review problem with one new problem to keep both recall and growth active.",
            cta: "Open recommendations",
            difficulty: suggestedProblems[0]?.difficulty || "EASY",
            estimatedMinutes: 30,
          };

  // Weekly plan (same as before)
  const weekdayTopics = candidateTopics.length
    ? candidateTopics
    : ["Arrays", "Hashing", "Two Pointers", "Sliding Window", "DP"];
  const weeklyPlan = [
    {
      day: "monday",
      topic: weekdayTopics[0],
      focus: "Core pattern",
      problems: [suggestedProblems[0]?.title || ""],
    },
    {
      day: "tuesday",
      topic: weekdayTopics[1] || weekdayTopics[0],
      focus: "Edge cases",
      problems: [suggestedProblems[1]?.title || ""],
    },
    {
      day: "wednesday",
      topic: weekdayTopics[2] || weekdayTopics[0],
      focus: "Complexity optimization",
      problems: [suggestedProblems[2]?.title || ""],
    },
    {
      day: "thursday",
      topic: weekdayTopics[3] || weekdayTopics[1] || weekdayTopics[0],
      focus: "Speed + correctness",
      problems: [suggestedProblems[3]?.title || ""],
    },
    {
      day: "friday",
      topic: weekdayTopics[4] || weekdayTopics[0],
      focus: "Mixed set",
      problems: [suggestedProblems[4]?.title || ""],
    },
    {
      day: "saturday",
      topic: "Mock interview",
      focus: "Explain before coding",
      problems: [],
    },
    {
      day: "sunday",
      topic: "Review",
      focus: "Revisit weak patterns",
      problems: [],
    },
  ];

  // Tips based on experience
  const tips = [];
  if (totalSolved < 5) {
    tips.push("Start with easy problems to build confidence and momentum.");
  } else if (avgScore < 50) {
    tips.push(
      "Review your incorrect submissions and focus on understanding mistakes.",
    );
  } else if (optimalCount / (totalSolved || 1) < 0.5) {
    tips.push(
      "Aim for more optimal solutions; revisit problems where your solution was not optimal.",
    );
  } else {
    tips.push(
      "Great job! Try mock interviews and timed practice for the next level.",
    );
  }

  return {
    weakTopics,
    suggestedProblems,
    weeklyPlan,
    tips,
    nextAction,
  };
};
